python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 256 \
  --hidden_dim 512 \
  --hidden_layers 3 \
  --num_blocks 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
 --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_192_96 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 128 \
  --hidden_dim 512 \
  --hidden_layers 3 \
  --num_blocks 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_288_144 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 512 \
  --hidden_dim 512 \
  --hidden_layers 3 \
  --num_blocks 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_384_192 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 64 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_48 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 64 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_192_96 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_288_144 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 3 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_384_192 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select



python -u run.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 128 \
  --hidden_dim 256 \
  --hidden_layers 3 \
  --num_blocks 4 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_192_96 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 3 \
  --num_blocks 4 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_288_144 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 512 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_384_192 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 64 \
  --hidden_dim 128 \
  --hidden_layers 3 \
  --num_blocks 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_48_24 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 48 \
  --pred_len 24 \
  --seg_len 24 \
  --dynamic_dim 128 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_72_36 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 72 \
  --pred_len 36 \
  --seg_len 36 \
  --dynamic_dim 512 \
  --hidden_dim 512 \
  --hidden_layers 3 \
  --num_blocks 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 256 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_120_60 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 120 \
  --pred_len 60 \
  --seg_len 60 \
  --dynamic_dim 64 \
  --hidden_dim 256 \
  --hidden_layers 4 \
  --num_blocks 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 512 \
  --hidden_dim 256 \
  --hidden_layers 3 \
  --num_blocks 1 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_192_96 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 64 \
  --hidden_dim 128 \
  --hidden_layers 2 \
  --num_blocks 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_288_144 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 128 \
  --hidden_dim 128 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_384_192 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 128 \
  --hidden_dim 128 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 128 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 4 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_192_96 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 64 \
  --hidden_dim 128 \
  --hidden_layers 3 \
  --num_blocks 2 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_288_144 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 128 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 2 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_384_192 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 128 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0 \
  --fourier select